name: Kinetic Build

on: [push, pull_request]

jobs:
  build-kinetic:
    runs-on: ubuntu-latest

    container:
      image: ros:kinetic-perception

    defaults:
      run:
        shell: bash

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Create Workspace
      run: |
        source /opt/ros/kinetic/setup.bash
        mkdir -p src_tmp/ && mv `find -maxdepth 1 -not -name . -not -name src_tmp` src_tmp/ && mv src_tmp/ src/
        cd src
        catkin_init_workspace
        cd ..

    - name: Install Dependencies
      run: |
        source /opt/ros/kinetic/setup.bash
        rosdep update && apt-get update -qqq
        rosdep install -y --from-paths src --ignore-src

    - name: Build Repo
      run: |
        source /opt/ros/kinetic/setup.bash
        catkin_make

    - name: Test Repo
      run: |
        source /opt/ros/kinetic/setup.bash
        catkin_make run_tests
        catkin_test_results --verbose
